export interface IProduct {
    id: number;
    name: string;
    price: number;
    description: string;
}
export const products: IProduct[] = [
    { id: 1, name: 'Phone XL', price: 799, description: 'A large phone with one of the best screens' },
    { id: 2, name: 'Phone Mini', price: 299, description: 'A small phone with a great camera' },
    { id: 3, name: 'Phone Pro', price: 999, description: 'A large phone with advanced features' },
    { id: 4, name: 'Phone Plus', price: 499, description: 'A mid-range phone with good camera' },
    { id: 5, name: 'Phone Max', price: 1999, description: 'A large phone with advanced camera' },
    { id: 6, name: 'Phone Nova', price: 1499, description: 'A large phone with advanced camera and battery' },
    { id: 7, name: 'Phone Nova 2', price: 1999, description: 'An updated version of the Nova phone' },
    { id: 8, name: 'Phone Nova 3', price: 2499, description: 'The latest and greatest version of the Nova phone' },
    { id: 9, name: 'Headphones Pro', price: 299, description: 'A pair of high quality headphones' },
    { id: 10, name: 'Headphones XL', price: 499, description: 'A pair of extra large headphones' },
    { id: 11, name: 'Tablet XS', price: 199, description: 'A small tablet with a great screen' },
    { id: 12, name: 'Tablet S', price: 299, description: 'A mid-range tablet with advanced features' },
    { id: 13, name: 'Tablet M', price: 499, description: 'A large tablet with a great screen' },
    { id: 14, name: 'Tablet L', price: 999, description: 'A large tablet with a great screen and advanced features' },
    { id: 15, name: 'Tablet XL', price: 1999, description: 'A large tablet with a great screen and advanced features' },
    { id: 16, name: 'Laptop XS', price: 2499, description: 'A small laptop with a great screen' },
    { id: 17, name: 'Laptop S', price: 2999, description: 'A mid-range laptop with advanced features' },
    { id: 18, name: 'Laptop M', price: 3999, description: 'A large laptop with a great screen and advanced features' },
    { id: 19, name: 'Laptop L', price: 4999, description: 'A large laptop with a great screen and advanced features' },
    { id: 20, name: 'Laptop XL', price: 5999, description: 'A large laptop with a great screen and advanced features' },
    {
        id: 21,
        name: 'Laptop Pro',
        price: 7999,
        description: 'A large laptop with a great screen and advanced features',
    },
    { id: 22, name: 'Laptop Max', price: 9999, description: 'The latest and greatest laptop' },
    { id: 23, name: 'Watch XS', price: 499, description: 'A small watch that is great for fitness tracking' },
    {
        id: 24,
        name: 'Watch S',
        price: 999,
        description: 'A mid-range watch that is great for fitness tracking and notifications',
    },
    {
        id: 25,
        name: 'Watch M',
        price: 1499,
        description: 'A large watch that is great for fitness tracking and notifications',
    },
    {
        id: 26,
        name: 'Watch L',
        price: 1999,
        description: 'A large watch that is great for fitness tracking and notifications',
    },
    { id: 27, name: 'Watch XL', price: 2999, description: 'The largest and most advanced watch on the market' },
    {
        id: 28,
        name: 'Smart Speaker',
        price: 299,
        description: 'A smart speaker that is great for voice control and music',
    },
    {
        id: 29,
        name: 'Smart Display',
        price: 999,
        description: 'A smart display that is great for watching movies and TV shows',
    },
    {
        id: 30,
        name: 'Smart Home Hub',
        price: 499,
        description: 'A smart home hub that is great for controlling lights and thermostats',
    },
    {
        id: 31,
        name: 'Smart Car',
        price: 1999,
        description: 'A smart car that is great for navigation and entertainment',
    },
    {
        id: 32,
        name: 'Smart Baby Monitor',
        price: 499,
        description: 'A smart baby monitor that is great for keeping an eye on your baby',
    },
    {
        id: 33,
        name: 'Smart Toilet',
        price: 1499,
        description: 'A smart toilet that is great for monitoring your water usage',
    },
    {
        id: 34,
        name: 'Smart Kitchen',
        price: 2499,
        description: 'A smart kitchen that is great for managing your cooking and cleaning',
    },
    {
        id: 35,
        name: 'Smart Bathroom',
        price: 1999,
        description: 'A smart bathroom that is great for managing your plumbing and hygiene',
    },
    {
        id: 36,
        name: 'Smart Pet Tracker',
        price: 2999,
        description: 'A smart pet tracker that is great for keeping an eye on your pet',
    },
    {
        id: 37,
        name: 'Smart Garden',
        price: 1499,
        description: 'A smart garden that is great for managing your plants and gardening',
    },
    {
        id: 38,
        name: 'Smart Outdoor Light',
        price: 999,
        description: 'A smart outdoor light that is great for controlling your outdoor lighting',
    },
    {
        id: 39,
        name: 'Smart Security Camera',
        price: 1999,
        description: 'A smart security camera that is great for monitoring your home',
    },
    {
        id: 40,
        name: 'Smart Pet Feeder',
        price: 1499,
        description: 'A smart pet feeder that is great for feeding your pet',
    },
    {
        id: 41,
        name: 'Smart Pet Water Dispenser',
        price: 1999,
        description: 'A smart pet water dispenser that is great for keeping your pet hydrated',
    },
    {
        id: 42,
        name: 'Smart Pet Bed',
        price: 2999,
        description: 'A smart pet bed that is great for keeping your pet comfortable',
    },
    {
        id: 43,
        name: 'Smart Pet Litter Box',
        price: 1499,
        description: 'A smart pet litter box that is great for keeping your pet clean',
    },
    {
        id: 44,
        name: 'Smart Pet Food Dispenser',
        price: 1999,
        description: 'A smart pet food dispenser that is great for feeding your pet',
    },
    {
        id: 45,
        name: 'Smart Pet Grooming Brush',
        price: 2999,
        description: 'A smart pet grooming brush that is great for keeping your pet clean',
    },
    {
        id: 46,
        name: 'Smart Pet Collars',
        price: 1499,
        description: 'A smart pet collar that is great for tracking your pet',
    },
    {
        id: 47,
        name: 'Smart Pet ID Tags',
        price: 1999,
        description: 'A smart pet ID tag that is great for identifying your pet',
    },
    {
        id: 48,
        name: 'Smart Pet Harness',
        price: 2999,
        description: 'A smart pet harness that is great for hiking and running errands',
    },
    {
        id: 49,
        name: 'Smart Pet Leash',
        price: 1499,
        description: 'A smart pet leash that is great for walking your pet',
    },
    {
        id: 50,
        name: 'Smart Pet Water Bowl',
        price: 1999,
        description: 'A smart pet water bowl that is great for keeping your pet hydrated',
    },
];
